## 利用GitHub Actions每天定时给百度推送链接，提高收录率 ##

name: baiduPush

# 两种触发方式：一、master分支更新，二、每天国际标准时间23点（北京时间+8即早上7点）运行
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 23 * * *' # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule
# on:
#   schedule:
#     - cron: '*/5 * * * *' # 每5分钟一次，测试用

jobs:
  bot:
    # 运行环境为最新版的Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 步骤一，获取仓库代码
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      # 步骤二，执行sh命令文件
      - name: 'Run baiduPush'
        run: npm install && npm run baiduPush # 运行目录是仓库根目录